# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Perpetual Musings
description: >- # this means to ignore newlines until "baseurl:"
  Thoughts of a average Techie
url: "https://yogeshpandey.in" # the base hostname & protocol for the site
disqus_shortname: yogesh-pandey
comments: true
reading_time:     true
words_per_minute: 120
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-58445322-1"

header:
  pages:
    - name: Home
      slug: /
    # - name: Work
    #   slug: /work
    - name: Tech
      slug: /tech
    - name: Travel
      slug: /travel
    - name: Other
      slug: /other

footer:
  show_powered_by: true
  contact:
    - name: Twitter
      link: http://twitter.com/yogeshmpandey
      username: "@yogeshmpandey"
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/yogeshmohanpandey
    - name: GitHub
      link: http://github.com/yogeshmpandey

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
