# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Yogesh Pandey
tagline:             General thoughts on everyhing that a mind can encapsulate
description:         WebLog of Yogesh Pandey
url:                 http://yogeshpandey.in
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Yogesh Pandey
  url:               https://twitter.com/yogesh__pandey
  email:             yogesh38726@gmail.com

# Custom vars
version:             0.0.1
