title:            Tech/Travel/Life
description:      Thoughts and Rants
disqus_shortname: yogesh-pandey
comments: true
reading_time:     true
words_per_minute: 120 
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:
# Owner/author information
owner:
  name:           Yogesh Pandey
  avatar:         avatar.jpg
  bio:            "General thoughts on probably everything"
  email:          yogesh38726@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        yogesh__pandey
  facebook:       yogeshmpandey
  github:         yogeshmpandey
  stackexchange:  
  linkedin:       
  instagram:      
  flickr:         
  tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:    +106772118865251041642

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-58445322-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Kolkata
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
  - jemoji
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 1

kramdown:
  auto_ids: true
  footnote_nr: 2
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
